<?php

use Illuminate\Database\Seeder;
use App\xmpTag;

class xmpTagsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$tags = array(
            /*-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-DC-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
            array(
                    'name'          => "format",
                    'label'         => "Format",
                    'prefix'        => "dc",
                    'type'          => "XmpText",
                    'valueType'     => null,
                    'category'      => "Internal",
                    'description'   => "",
                    'bind'          => "image",
                    'readonly'      => true,
                    'enumeration'   => null ),
            array(
                    'name'          => "subject",
                    'label'         => "Subject",
                    'prefix'        => "dc",
                    'type'          => "XmpBag",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "description",
                    'label'         => "Description",
                    'prefix'        => "dc",
                    'type'          => "LangAlt",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "creator",
                    'label'         => "Creator",
                    'prefix'        => "dc",
                    'type'          => "XmpSeq",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "title",
                    'label'         => "Title",
                    'prefix'        => "dc",
                    'type'          => "LangAlt",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "rights",
                    'label'         => "Rights",
                    'prefix'        => "dc",
                    'type'          => "LangAlt",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "publisher",
                    'label'         => "Publisher",
                    'prefix'        => "dc",
                    'type'          => "XmpBag",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "identifier",
                    'label'         => "Identifier",
                    'prefix'        => "dc",
                    'type'          => "XmpText",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "contributor",
                    'label'         => "Contributor",
                    'prefix'        => "dc",
                    'type'          => "XmpBag",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "date",
                    'label'         => "Date",
                    'prefix'        => "dc",
                    'type'          => "XmpSeq",
                    'valueType'     => "Date",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "YYYY-MM-DD",
                    'readonly'      => false,
                    'enumeration'   => null ),
            /*-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-XMP-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
            array(
                    'name'          => "Advisory",
                    'label'         => "Advisory",
                    'prefix'        => "xmp",
                    'type'          => "XmpBag",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "BaseURL",
                    'label'         => "Base URL",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => "URL",
                    'category'      => "Internal",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CreateDate",
                    'label'         => "Create Date",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => "Date",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "YYYY-MM-DDTh:mm:ss",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CreatorTool",
                    'label'         => "Creator Tool",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => null,
                    'category'      => "Internal",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "Identifier",
                    'label'         => "Identifier",
                    'prefix'        => "xmp",
                    'type'          => "XmpBag",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "Label",
                    'label'         => "Label",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "MetadataDate",
                    'label'         => "Metadata Date",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => "Date",
                    'category'      => "Internal",
                    'description'   => "",
                    'bind'          => "YYYY-MM-DDTh:mm:ss",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "ModifyDate",
                    'label'         => "Modify Date",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => "Date",
                    'category'      => "Internal",
                    'description'   => "",
                    'bind'          => "YYYY-MM-DDTh:mm:ss",
                    'readonly'      => false,
                    'enumeration'   => null ),
            array(
                    'name'          => "Nickname",
                    'label'         => "Nickname",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "Rating",
                    'label'         => "Rating",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => "ClosedChoice",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => json_encode([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])),
            array(
                    'name'          => "Thumbnails",
                    'label'         => "Thumbnails",
                    'prefix'        => "xmp",
                    'type'          => "XmpText",
                    'valueType'     => null,
                    'category'      => "Internal",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
/*-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-xmpRights-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
            array(
                    'name'          => "Certificate",
                    'label'         => "Certificate",
                    'prefix'        => "xmpRights",
                    'type'          => "XmpText",
                    'valueType'     => "URL",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "Marked",
                    'label'         => "Marked",
                    'prefix'        => "xmpRights",
                    'type'          => "XmpText",
                    'valueType'     => "Boolean",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "Owner",
                    'label'         => "Owner",
                    'prefix'        => "xmpRights",
                    'type'          => "XmpBag",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "UsageTerms",
                    'label'         => "Usage Terms",
                    'prefix'        => "xmpRights",
                    'type'          => "LangAlt",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "WebStatement",
                    'label'         => "Web Statement",
                    'prefix'        => "xmpRights",
                    'type'          => "XmpText",
                    'valueType'     => "URL",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
/*-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-Exif Schema for TIFF-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
            array(
                    'name'          => "Artist",
                    'label'         => "Artist",
                    'prefix'        => "tiff",
                    'type'          => "XmpText",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "Copyright",
                    'label'         => "Copyright",
                    'prefix'        => "tiff",
                    'type'          => "LangAlt",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
/*-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-IPTC Core-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
            array(
                    'name'          => "CreatorContactInfo",
                    'label'         => "Creator's Contact Info",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => null,
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CiAdrExtadr",
                    'label'         => "Contact Info-Address",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CiAdrCity",
                    'label'         => "Contact Info-City",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CiAdrRegion",
                    'label'         => "Contact Info-State/Province",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CiAdrPcode",
                    'label'         => "Contact Info-Postal Code",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CiAdrCtry",
                    'label'         => "Contact Info-Country",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CiEmailWork",
                    'label'         => "Contact Info-Email",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
            array(
                    'name'          => "CiTelWork",
                    'label'         => "Contact Info-Phone",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
             array(
                    'name'          => "CiUrlWork",
                    'label'         => "Contact Info-Web URL",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),
              array(
                    'name'          => "IntellectualGenre",
                    'label'         => "Intellectual Genre",
                    'prefix'        => "Iptc4xmpCore",
                    'type'          => "XmpText",
                    'valueType'     => "Text",
                    'category'      => "External",
                    'description'   => "",
                    'bind'          => "",
                    'readonly'      => false,
                    'enumeration'   => null),

//Scene https://www.exiv2.org/tags-xmp-iptc.html
        );

//id, name , 'label', prefix, type, | valueType, category, description, bind, readonly, enumeration

        xmpTag::insert($tags);
    }
}
